version: 0.0
os: linux
files:
  - source: /
    destination: /dummy
hooks:
  BeforeInstall:
    - location: scripts/update.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/update.sh
      timeout: 300
      runas: ubuntu
