version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
  BeforeInstall:
    - location: scripts/update.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start.sh
      timeout: 300
      runas: root
